# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4caab5905ca16fec72ca58c51bb68b9ff4f8e1bdde66ef0346833b7e26e17c2e5042cb7ecfd64a5480dacfdf737ac8c5336a17b8f5d74f66d5517f327bcd871

test:
  secret_key_base: 251da98f7a5504bc7555f4fdca16d3a2264e16ca588ee56d9819ff87c78d452c5e42b2ef6e5d0f3e04e31faa0f5a3dfaacacaba1fc08fd553e53cf0bfaac92ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
